ALTER TYPE "TaskActivityType" ADD VALUE 'TITLE_CHANGED';
ALTER TYPE "TaskActivityType" ADD VALUE 'DESCRIPTION_CHANGED';
ALTER TYPE "TaskActivityType" ADD VALUE 'WATCHER_ADDED';
ALTER TYPE "TaskActivityType" ADD VALUE 'WATCHER_REMOVED';
ALTER TYPE "TaskActivityType" ADD VALUE 'ATTACHMENT_ADDED';
ALTER TYPE "TaskActivityType" ADD VALUE 'ATTACHMENT_REMOVED';
